apiVersion: v1
kind: Service
metadata:
  name: techmarket-orders-service
spec:
  type: LoadBalancer
  selector:
    app: techmarket-orders-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80